services:
  myhome:
    build:
      context: .
      dockerfile: MyHomeBlazorApp/Dockerfile
    image: lyseriuos/myhomeblazorapp:latest
    container_name: myhome
    ports:
      - "7211:8080"
    volumes:
      - myhome-data:/app/BlazorData
      - myhome-files:/app/Files
      - myhome-keys:/home/app/.aspnet/DataProtection-Keys
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    restart: unless-stopped

volumes:
  myhome-data:
  myhome-files:
  myhome-keys: